### PR TITLE
Updated zoom

### PR DESCRIPTION
**Pull request by mikecole**

### CODE REVIEW

**Comment by mikecole** [comment]
@meek2100 I got the following error: 

`Search pattern not found: '(^[$]checksum\s*=\s*)('.*')' (11.15s)`

**Comment by meek2100** [comment]
I'm pretty sure that is because the "tools" directory and the "ChocolateyInstall.ps1" file is no longer in this the "automatic/zoom" directory, so AU is searching for the checksum section of the ChocolateyInstall.ps1 file and unable to locate it.

**Comment by mikecole** [comment]
LOL facepalm on my part.

**Comment by meek2100** [comment]
No worries.  I only validated the URL part as I don't have a full copy of this locally to validate all the AU variables, so I just assumed everything else should still be working there. 

Here is what I ran in powershell:
$download_page_url = 'https://zoom.us/download#client_4meeting'
$url_part1 = 'https://zoom.us/client/'
$url_part2 = '/ZoomInstallerFull.msi'
$homepage_content = Invoke-WebRequest -UseBasicParsing -Uri $download_page_url
$homepage_content -match '(Version \d+\.\d+\.\d (\(\d+\.\d+\)))'| Out-Null
$recodeversion = $matches[1] -replace "Version ", ""
$version = $recodeversion.Substring(0,4) + $recodeversion.Substring(7,10)
$url = $url_part1 + $version + $url_part2
$url

If you are still having issues after restoring the tools directory and the chocolateyinstall.ps1 file let me know and I'm happy to help debug it further.

**Comment by mikecole** [comment]
Sounds good, I'm working on it now. Thanks.

**Comment by mikecole** [comment]
So far so good, I'll let it get through the choco validation process and then I'll work on restoring it from deprecation.

**Comment by meek2100** [comment]
Sounds good.  Just ping me, if you need help with anything else on it. It should hopefully be good now, assuming Zoom doesn't go changing their version number again.  But if they do it should just break the auto update rather than pushing up the wrong info to Chocolatey.

**Pull request merged**
