### PR TITLE
Add tools parameters for ssdt15

### PR DESCRIPTION
**Pull request by kwlin**
Hi,

I've added feature/tools flags for ssdt15. It's untested :( but it's based on the following [walkthrough](https://chocolatey.org/docs/how-to-parse-package-parameters-argument) from chocolatey. 

Please let me know if it works, so I can arguments to the ssdt17 choco package :)

### CODE REVIEW

**Comment by mikecole** [comment]
It looks solid. I'll try to get it tested on a VM sometime this week. Thanks for doing this!

**Comment by kwlin** [comment]
Any luck testing my changes? :)

**Comment by mikecole** [comment]
I'm sorry, I haven't gotten around to it yet. If you'd like I'd be happy to make you co-maintainer of the package if you wanted to test/submit yourself. Otherwise I'll try to get to it soon.

**Comment by mikecole** [comment]
@kwlin Please change the version in the nuspec file to 14.0.61712.20180510. This will ensure that this new package will be the latest.

Other than that, it worked great! Question: in the absence of params, would you expect ALL features to be installed, or NO features?

**Comment by kwlin** [comment]
Interesting question. 

I've tested the command line on a machine without visual studio and it just installed Visual Studio Integrated Shell. So it seems it just install without any features.

```
[104C:4158][2018-05-12T22:55:02]: Burn v3.6.3542.0, Windows v6.3 (Build 9600: Service Pack 0), path: C:\temp\SSDTSetup.exe, cmdline: '/passive /log c:\temp\log.txt /norestart'
[104C:4158][2018-05-12T22:55:02]: Initializing numeric variable 'InstallLanguage' to value '1033'
[104C:4158][2018-05-12T22:55:02]: Initializing numeric variable 'EnglishLanguage' to value '1033'
[104C:4158][2018-05-12T22:55:02]: Initializing numeric variable 'INSTALLINTEGRATEDSHELL' to value '1'
[104C:4158][2018-05-12T22:55:02]: Initializing numeric variable 'INSTALLAS' to value '0'
[104C:4158][2018-05-12T22:55:02]: Initializing numeric variable 'INSTALLRS' to value '0'
[104C:4158][2018-05-12T22:55:02]: Initializing numeric variable 'INSTALLIS' to value '0'
[104C:4158][2018-05-12T22:55:02]: Initializing numeric variable 'INSTALLALL' to value '0'
[104C:4158][2018-05-12T22:55:02]: Initializing numeric variable 'SKIPENVIRONMENTSETUP' to value '0'
[104C:4158][2018-05-12T22:55:02]: Initializing numeric variable 'INSTALLSHORTCUT' to value '1'
[104C:4158][2018-05-12T22:55:02]: Initializing numeric variable 'TELEMETRYOPTIN' to value '1'
[104C:4158][2018-05-12T22:55:03]: Setting string variable 'WixBundleLog' to value 'c:\temp\log.txt'
[104C:4158][2018-05-12T22:55:03]: Setting string variable 'WixBundleOriginalSource' to value 'C:\temp\SSDTSetup.exe'
[104C:4158][2018-05-12T22:55:03]: Setting string variable 'WixBundleName' to value 'Microsoft SQL Server Data Tools - Visual Studio 2015'
[104C:418C][2018-05-12T22:55:03]: Ignoring unknown argument: ignored
[104C:4158][2018-05-12T22:55:03]: Detect 45 packages
[104C:4158][2018-05-12T22:55:03]: Registry key not found. Key = 'SOFTWARE\Microsoft\DevDiv\vs\Servicing\14.0\devenv'

...

```

Is it better to change the default behavior to install a feature? Or just keep it this way?

**Comment by mikecole** [comment]
Let’s keep as is. The user can opt in instead of opting out. Once the
version is updated I’ll merge and submit to choco.

Thanks again!!

**Comment by kwlin** [comment]
Nuspec version & description  changed. 

What kind of convention are you using for the nuspec version? I'll try to make a pull request for SSDT16 asap :)

**Comment by mikecole** [comment]
I generally try to make the nuspec match the package version, and if I need to roll out a fix to an existing version I use the current date as the 4th segment.

Thanks!!

**Pull request merged**
