### PR TITLE
Start PMS after update

### PR DESCRIPTION
**Pull request by bcurran3**
This is untested.
-----------------
This should test to see if PMS is running before an update and run it again after the update if so. It should not run PMS if it wasn't previously installed and running.
-----------------
I'll test when I have a chance.

### CODE REVIEW

**Comment by bcurran3** [comment]
opened different PR with changes

**Comment by mikecole** [comment]
Hey Bill, thanks for the pull request, and sorry for the late response. I ran into some issues testing this today, but I'm hoping to have that resolved soon. I appreciate your patience!

**Comment by mikecole** [comment]
Tested and merged. Thanks!

**Pull request merged**
