### PR TITLE
DirectX 9 installation  - non working Microsoft URL

### PR DESCRIPTION
**Pull request by tapika**
Non working Microsoft URL anymore, use local installation file instead

### CODE REVIEW

**Comment by tapika** [comment]
I haven't received any clear answer why that link is broken. If you know correct guys on Microsoft side to whom to contact, let me know.

FYI:

https://docs.microsoft.com/en-us/answers/questions/249153/directx-9-wont-install-on-windows-10-12021.html

https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_install/directx-9-wont-install-on-windows-10-12021/8511cba9-01e7-4fbb-9d07-7629f82c3b60

**Comment by mikecole** [comment]
There are issues with redistribution rights when including the installer locally, so I need to get that cleared up first.

**Comment by tapika** [comment]
> There are issues with redistribution rights when including the installer locally, so I need to get that cleared up first.

You will do something ? Or should I and what ?

**Comment by mikecole** [comment]
Let's leave this open and I'll try to get the redistributable issue sorted out.

**Comment by tapika** [comment]
I've tried to locate direct x end user license or something what remains me of that one, but could not find any on internet.

but after launching `directx_Jun2010_redist.exe` - I've located following text:

```
MICROSOFT SOFTWARE LICENSE TERMS
MICROSOFT DIRECTX SOFTWARE DEVELOPMENT KIT (SDK)
These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you.  Please read them.  They apply to the software named above, which includes the media on which you received it, if any.  The terms also apply to any Microsoft
•	updates,
•	supplements,
•	Internet-based services, and 
•	support services
for this software, unless other terms accompany those items.  If so, those terms apply.
BY USING THE SOFTWARE, YOU ACCEPT THESE TERMS.  IF YOU DO NOT ACCEPT THEM, DO NOT USE THE SOFTWARE.
If you comply with these license terms, you have the rights below.
1.	INSTALLATION AND USE RIGHTS.  
a.	Installation and Use.  You may install and use any number of copies of the software on your devices.
b.	Included Microsoft Programs.  The software contains other Microsoft programs.  The license terms with those programs apply to your use of them.
2.	ADDITIONAL LICENSING REQUIREMENTS AND/OR USE RIGHTS.
a.	Media Elements and Templates.  You may copy and use images, clip art, animations, sounds, music, shapes, video clips and templates provided with the software and identified for such use in documents and projects that you create.  You may distribute those documents and projects non-commercially.  If you wish to use these media elements or templates for any other purpose, go to www.microsoft.com/permission to learn whether that use is allowed.
b.	Distributable Code.  The software contains code that you are permitted to distribute in programs you develop if you comply with the terms below.
i.	Right to Use and Distribute.  The code and text files listed below are “Distributable Code.”
•	DIRECTX REDIST.TXT Files.  You may copy and distribute the object code form of code listed in DIRECTX REDIST.TXT files.
•	Sample Code.  You may modify, copy, and distribute the source and object code form of code marked as “sample”, as well as those marked as follows:
\Utilities\bin\x86\dxerr
\Utilities\bin\x64\dxerr
\Utilities\bin\x86\dxtex
\Utilities\bin\x64\dxtex
\Utilities\bin\x86\DxViewer
\Utilities\bin\x64\DxViewer
\Utilities\bin\x86\GDFTrace
\Utilities\bin\x64\GDFTrace
\Utilities\bin\x86\MeshConvert
\Utilities\bin\x64\MeshConvert
\Utilities\Source\Sas
\Utilities\Source\Effects11
•	Third Party Distribution.  You may permit distributors of your programs to copy and distribute the Distributable Code as part of those programs.
ii.	Distribution Requirements.  For any Distributable Code you distribute, you must
•	add significant primary functionality to it in your programs;
•	require distributors and external end users to agree to terms that protect it at least as much as this agreement; 
•	display your valid copyright notice on your programs; and
•	indemnify, defend, and hold harmless Microsoft from any claims, including attorneys’ fees, related to the distribution or use of your programs.
iii.	Distribution Restrictions.  You may not
•	alter any copyright, trademark or patent notice in the Distributable Code; 
•	use Microsoft’s trademarks in your programs’ names or in a way that suggests your programs come from or are endorsed by Microsoft; 
•	distribute Distributable Code to run on a platform other than the Windows, Xbox and Windows Mobile platforms;
•	include Distributable Code in malicious, deceptive or unlawful programs; or
•	modify or distribute the source code of any Distributable Code so that any part of it becomes subject to an Excluded License.  An Excluded License is one that requires, as a condition of use, modification or distribution, that
•	the code be disclosed or distributed in source code form; or 
•	others have the right to modify it.
3.	SCOPE OF LICENSE.  The software is licensed, not sold. This agreement only gives you some rights to use the software.  Microsoft reserves all other rights.  Unless applicable law gives you more rights despite this limitation, you may use the software only as expressly permitted in this agreement.  In doing so, you must comply with any technical limitations in the software that only allow you to use it in certain ways.    You may not
•	disclose the results of any benchmark tests of the software to any third party without Microsoft’s prior written approval;
•	work around any technical limitations in the software;
•	reverse engineer, decompile or disassemble the software, except and only to the extent that applicable law expressly permits, despite this limitation;
•	make more copies of the software than specified in this agreement or allowed by applicable law, despite this limitation;
•	publish the software for others to copy;
•	rent, lease or lend the software; or
•	use the software for commercial software hosting services.
4.	BACKUP COPY.  You may make one backup copy of the software.  You may use it only to reinstall the software.
5.	DOCUMENTATION.  Any person that has valid access to your computer or internal network may copy and use the documentation for your internal, reference purposes.
6.	EXPORT RESTRICTIONS.  The software is subject to United States export laws and regulations.  You must comply with all domestic and international export laws and regulations that apply to the software.  These laws include restrictions on destinations, end users and end use.  For additional information, see www.microsoft.com/exporting.
7.	SUPPORT SERVICES. Because this software is “as is,” we may not provide support services for it.
8.	ENTIRE AGREEMENT.  This agreement, and the terms for supplements, updates, Internet-based services and support services that you use, are the entire agreement for the software and support services.
9.	APPLICABLE LAW.
a.	United States.  If you acquired the software in the United States, Washington state law governs the interpretation of this agreement and applies to claims for breach of it, regardless of conflict of laws principles.  The laws of the state where you live govern all other claims, including claims under state consumer protection laws, unfair competition laws, and in tort.
b.	Outside the United States.  If you acquired the software in any other country, the laws of that country apply.
10.	LEGAL EFFECT.  This agreement describes certain legal rights.  You may have other rights under the laws of your country.  You may also have rights with respect to the party from whom you acquired the software.  This agreement does not change your rights under the laws of your country if the laws of your country do not permit it to do so.
11.	DISCLAIMER OF WARRANTY.   THE SOFTWARE IS LICENSED “AS-IS.”  YOU BEAR THE RISK OF USING IT.  MICROSOFT GIVES NO EXPRESS WARRANTIES, GUARANTEES OR CONDITIONS.  YOU MAY HAVE ADDITIONAL CONSUMER RIGHTS UNDER YOUR LOCAL LAWS WHICH THIS AGREEMENT CANNOT CHANGE.  TO THE EXTENT PERMITTED UNDER YOUR LOCAL LAWS, MICROSOFT EXCLUDES THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
12.	LIMITATION ON AND EXCLUSION OF REMEDIES AND DAMAGES.  YOU CAN RECOVER FROM MICROSOFT AND ITS SUPPLIERS ONLY DIRECT DAMAGES UP TO U.S. $5.00.  YOU CANNOT RECOVER ANY OTHER DAMAGES, INCLUDING CONSEQUENTIAL, LOST PROFITS, SPECIAL, INDIRECT OR INCIDENTAL DAMAGES.
This limitation applies to
•	anything related to the software, services, content (including code) on third party Internet sites, or third party programs; and
•	claims for breach of contract, breach of warranty, guarantee or condition, strict liability, negligence, or other tort to the extent permitted by applicable law.
It also applies even if Microsoft knew or should have known about the possibility of the damages.  The above limitation or exclusion may not apply to you because your country may not allow the exclusion or limitation of incidental, consequential or other damages.
Please note: As this software is distributed in Quebec, Canada, some of the clauses in this agreement are provided below in French.
Remarque : Ce logiciel étant distribué au Québec, Canada, certaines des clauses dans ce contrat sont fournies ci-dessous en français.
EXONÉRATION DE GARANTIE. Le logiciel visé par une licence est offert « tel quel ». Toute utilisation de ce logiciel est à votre seule risque et péril. Microsoft n’accorde aucune autre garantie expresse. Vous pouvez bénéficier de droits additionnels en vertu du droit local sur la protection des consommateurs, que ce contrat ne peut modifier. La ou elles sont permises par le droit locale, les garanties implicites de qualité marchande, d’adéquation à un usage particulier et d’absence de contrefaçon sont exclues.
LIMITATION DES DOMMAGES-INTÉRÊTS ET EXCLUSION DE RESPONSABILITÉ POUR LES DOMMAGES.  Vous pouvez obtenir de Microsoft et de ses fournisseurs une indemnisation en cas de dommages directs uniquement à hauteur de 5,00 $ US. Vous ne pouvez prétendre à aucune indemnisation pour les autres dommages, y compris les dommages spéciaux, indirects ou accessoires et pertes de bénéfices.
Cette limitation concerne :
•	tout  ce qui est relié au logiciel, aux services ou au contenu (y compris le code) figurant sur des sites Internet tiers ou dans des programmes tiers ; et
•	les réclamations au titre de violation de contrat ou de garantie, ou au titre de responsabilité stricte, de négligence ou d’une autre faute dans la limite autorisée par la loi en vigueur.
Elle s’applique également, même si Microsoft connaissait ou devrait connaître l’éventualité d’un tel dommage.  Si votre pays n’autorise pas l’exclusion ou la limitation de responsabilité pour les dommages indirects, accessoires ou de quelque nature que ce soit, il se peut que la limitation ou l’exclusion ci-dessus ne s’appliquera pas à votre égard.
EFFET JURIDIQUE.  Le présent contrat décrit certains droits juridiques. Vous pourriez avoir d’autres droits prévus par les lois de votre pays.  Le présent contrat ne modifie pas les droits que vous confèrent les lois de votre pays si celles-ci ne le permettent pas.
```

I guess what is relevant from our perspective is:

1.	INSTALLATION AND USE RIGHTS.  
a.	Installation and Use.  You may install and use any number of copies of the software on your devices.

**Comment by mikecole** [comment]
That seems reasonable to me. I’ll give it a shot and see what the
moderators decide. I believe there’s an extra file they like included in
the package in cases like these. I’ll check the docs to try to find that.

**Comment by tapika** [comment]
> That seems reasonable to me. I’ll give it a shot and see what the moderators decide. I believe there’s an extra file they like included in the package in cases like these. I’ll check the docs to try to find that.

Please note that in latest .ps1 script I've reconfigured to delete everything after installation.

Basically package contains install package, and there is no reason to keep *.nupkg, *.nuspec, *.exe, as it's installed to windows, and it's not possible to uninstall it. Means also no reason to keep anything on disk after installation.

License maybe could be kept, but not sure if it's needed - could be may displayed as url link - if you want to see EULA, go on this web page or something like that.

**Comment by mikecole** [comment]
I pushed to moderation. Let's see what happens.

**Comment by tapika** [comment]
Hmm...  Do you rebuild packages or should I do it and so I have rights to update them ?

https://chocolatey.org/packages/directx

this is quite old package, and was not fixed because of merge?

**Comment by mikecole** [comment]
I pushed the package to moderation 2 days ago. I received a message this morning that they can't accept this package for a few reasons:

1) the VERIFICATION.txt should allow a moderator to validate/reproduce how to get the binary files. I know this may be really unfortuante in the current case, yet we need to be able to check the origin of the binaries somehow.

2) the executable embedded in the package is not explicitly stated in the license, it only states 'redistributable code', without explicit consent from the software vendor, it's not allowed to include those artifacts in a package.

At this point I don't know the path forward unless you have a contact at Microsoft that can OK including this package. I asked the moderator for further advice on how to proceed as well.

**Comment by tapika** [comment]
As for 1 - it could be easily added, the 2 point and comment after that is a blocker for me.

I've posted one more question in this forum:

https://answers.microsoft.com/en-us/windows/forum/all/directx-9-installation-is-missing-for-windows-10/660da2ba-574e-40de-9eda-599580560e74

But I do not have any direct contacts on Microsoft side, which would be dealing with Direct X.

**Comment by tapika** [comment]
I've scanned through git for developers from Microsoft with open e-mail, and found and got following reply:

```
From: Claire Andrews <clandrew@microsoft.com>
To: Tarmo Pikaro <tapika@yahoo.com>
Sent: Wednesday, February 3, 2021, 11:29:31 PM GMT+2
Subject: RE: [EXTERNAL] Direct X 9 installation on Windows 10...

Hello, I definitely recognize the inconvenience. The removal of the DirectX 9 end user runtime download page came as a surprise to me also.

Maybe this blog post will help:

https://walbourn.github.io/where-is-the-directx-sdk-2021-edition/
```

As last link there is given `DXSDK_Jun10.exe` with it's sha256 checksum. 

It's full DirectX SDK, but this package targets for full SDK, and end-users normally does not need it.

I've installed `DXSDK_Jun10.exe`, and find out that in 
`C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Redist`

there exists same kind installer as in `directx_Jun2010_redist.exe` - `directx_Jun2010_redist.exe` is self-extracting executable, which extracts same files as in `C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Redist`.


`C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Documentation\License Agreements`

folder also includes more license agreements - maybe contains more information.

(Will attach those files shortly).

Theoretically in `chocolateyInstall.ps1` currently I have double extraction:

```
Install-ChocolateyPackage @packageArgs

# Run the actual installer
$dxSetup = Join-Path $tempDir 'DXSETUP.exe'
Install-ChocolateyInstallPackage 'directx' 'exe' '/silent' "$dxSetup"
```

where 1 `Install-ChocolateyPackage` call to is extracting from self-extracting executable, and 2 `Install-ChocolateyPackage` is install itself.

I can remove 1 completely and leave only 2 call with the same file set as in `C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Redist`.

Then we come to question of licensing and allowing to distribute - based on attached files - can you say whether we are allowed to re-distribute given files ?

**Comment by tapika** [comment]
[License Agreements.zip](https://github.com/mikecole/chocolatey-packages/files/5936902/License.Agreements.zip)

**Pull request merged**
