### PR TITLE
Update update.ps1

### PR DESCRIPTION
**Pull request by meek2100**
This should fix your AU issues and change it so you can point to a version specific update instead of just latest.

---
You could also use the URL parts below, but I'm not sure if this URL will remain consistent in the future.

url_part1 = 'https://d11yldzmag5yn.cloudfront.net/prod/'
url_part2 = '/ZoomInstallerFull.msi'

### CODE REVIEW

**Review by mikecole — APPROVED** [review]

**Comment by mikecole** [comment]
Can you also remove the .rem on the filename to re-active it?

**Comment by meek2100** [comment]
Done.

**Comment by mikecole** [comment]
@meek2100 Are you aware of a list of these version available? How are you determining the download URL of a package? 

Currently listed is **Version 4.5.7 (5699.1027)**, which looks to me should build the following URL: `https://zoom.us/client/4.5.75699.1027/ZoomInstallerFull.msi`. That URL fails though. Am I missing something?

**Comment by meek2100** [comment]
Looks like it isn't quite stripping enough the 7 shouldn't be there.

The version should be 4.5.75699.1027 then it will work correctly. I'll adjust this.

**Comment by meek2100** [comment]
It is odd that it isn't working correctly for you when I test it directly in Powershell it gets the correct URL, but I'll still adjust it to remove one more character to get rid of the "7".

$download_page_url = 'https://zoom.us/download#client_4meeting'
$url_part1 = 'https://zoom.us/client/'
$url_part2 = '/ZoomInstallerFull.msi'
$homepage_content = Invoke-WebRequest -UseBasicParsing -Uri $download_page_url
$homepage_content -match '(Version \d+.\d+.\d+.\d+)'| Out-Null
$version = $matches[1] -replace "Version ", ""
$homepage_content -match '(Version \d+.\d+.\d (\(.\d+.\d+\)))'| Out-Null
$recodeversion = $matches[1] -replace "Version ", ""
$version = $recodeversion.Substring(0,4) + $recodeversion.Substring(7,9)
$url = $url_part1 + $version + $url_part2
$version
4.5.5699.1027
$url
https://zoom.us/client/4.5.5699.1027/ZoomInstallerFull.msi

**Comment by mikecole** [comment]
Sorry for the misunderstanding. I didn't actually run it. I was attempting to figure out the URL scheme.

**Comment by meek2100** [comment]
Oh, haha.  I'll go close the other pull request then, I thought this was broken somehow.

Yeah, it is 4.5.x replace "x" with the actual build number inside the parenthesis. They haven't changed their build system they just tried to create a user friendly version number for some reason. So the "7" in Version 4.5.7 (5699.1027) is artificial. This could break in the future if they actually change the build system or start hiding the build number, but I would be surprised if they every reversion their build system entirely.

**Comment by meek2100** [comment]
BTW here is the list of all past versions: https://support.zoom.us/hc/en-us/articles/201361953-New-Updates-for-Windows

**Pull request merged**
