### PR TITLE
Update zoom.nuspec

### PR DESCRIPTION
**Pull request by meek2100**

### CODE REVIEW

**Comment by mikecole** [comment]
I know the version # is wrong, but I don't know what to do about it at this point, except wait for the real version number to catch up. I'm not sure what this format of version # will do? I don't think it will work.

**Comment by mikecole** [comment]
This is a lower version than what's already posted, so I don't see the advantage of pushing this. I could push this and delist all of the incorrect packages, but that would break current users I think.

**Comment by meek2100** [comment]
Understood, but will the version ever catch up if you keep updating the 4.8.xxxx.xxxx version?  Wouldn't continuing down this path just continue to break new users as well as existing?  I could misunderstand or be totally wrong here. Just trying to help get this working for everyone again.  

Thanks for putting it together in the 1st place.

**Comment by mikecole** [comment]
I don't think it's broken now. It should be working, and the update path should be working for everybody (when I finally update the version). The only problem is the version number is wrong, because they changed their site and the HTML scraper that grabs the version got the next products version instead. I really just need to reach out to the mods to get their advice on how to handle it.

**Comment by mikecole** [comment]
I might be wrong about my assumptions too. I do appreciate your interest in fixing the situation.

**Comment by meek2100** [comment]
Hi,

Thanks for your email.

Unfortunately, we cannot remove package versions. What can be done is to remove the package versions that are incorrect and submit new package versions. However, what needs to be remembered is that Chocolatey only upgrades to a newer package version. So, as an example, if you released v6 which I downloaded and installed. You then notice that it's a mistake and should have been v5 you can then submit v5. Because my version is higher (v6) I'll never get that version, or any of the v5.1, v5.2 etc. versions you release either. I will only get the next version you release AFTER 6 (so 6.01, 6.1 etc.).

Does that make sense?

Kind regards,

Paul Broadwith
Chocolatey Software
3620 SW Fairlawn Rd, Suite #220
Topeka, KS
66614
T: +1 (785) 783-4720
W: chocolatey.io
Software Management Automation
<http://chocolatey.io/>



On Fri, 25 Oct 2019 at 23:48, '' meek2100' via Chocolatey.org' via chocolatey-moderators <chocolatey-moderators@googlegroups.com<mailto:chocolatey-moderators@googlegroups.com>> wrote:

User (meek2100) is reporting on 'zoom' version '4.8.5336.0929'.
left the following information in the report:

Hi,
Is there a way to remove packages that were versioned incorrectly? On the Zoom Client for Meetings it scraped the wrong version and now the package released is the Outlook version number instead of the client version number. If the last 3 packages were removed or re-versioned it would resolve the issue as the code on GitHub has been fixed to get the correct version again. I contacted the package maintainer, but he wasn't sure how to fix it.

Chocolatey Package: https://chocolatey.org/packages/zoom
Zoom Download Page: https://zoom.us/download#client_4meeting
Actual current Version Zoom Client: Version 4.5.5666.1020 OR Version 4.5.6 (5666.1020)

Incorrect Versions of the Zoom Client that are screwing things and should be corrected or removed:
-Zoom Client for Meetings 4.8.5336.0930 7 Friday, October 25, 2019 Waiting for Maintainer gravatar
-Zoom Client for Meetings 4.8.5336.0929 12913 Monday, October 7, 2019 Approved
-Zoom Client for Meetings 4.8.5336.0928 19600 Sunday, September 29, 2019

Message sent from Chocolatey.org

Current Maintainer(s): cole.mike, Sparticuz
Package Url: https://chocolatey.org/packages/zoom/4.8.5336.0929

On Fri, Oct 25, 2019 at 4:16 PM Mike Cole <notifications@github.com<mailto:notifications@github.com>> wrote:

I might be wrong about my assumptions too. I do appreciate your interest in fixing the situation.

**Comment by mikecole** [comment]
Thanks for the research. Seems like we're stuck then until the versions catch up (if they do)? I'm not sure of another alternative.

**Comment by meek2100** [comment]
Yep, looks that way.

On Mon, Oct 28, 2019 at 9:30 AM Mike Cole <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for the research. Seems like we're stuck then until the versions catch up (if they do)? I'm not sure of another alternative.

**Pull request closed without merging**
